routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group( ["middleware" => ['auth']], function(){
    Route::post('change-password', [App\Http\Controllers\UserController::class, 'updatePassword']);
});

Route::group( ["middleware" => ['auth',"role:Super Admin|Admin Sucursales"]], function(){
    Route::get('usuarios', [App\Http\Controllers\UserController::class, 'index']);
    Route::post('save-user', [App\Http\Controllers\UserController::class, 'store']);
    Route::post('update-user', [App\Http\Controllers\UserController::class, 'update']);
    Route::post('delete-user', [App\Http\Controllers\UserController::class, 'delete']);
    Route::get('bitacora', [App\Http\Controllers\BitacoraController::class, 'index']);
    Route::post('show-bitacora', [App\Http\Controllers\BitacoraController::class, 'show']);

    Route::get('campus', [App\Http\Controllers\CampusController::class, 'index']);
    Route::post('save-campus', [App\Http\Controllers\CampusController::class, 'store']);
    Route::post('update-campus', [App\Http\Controllers\CampusController::class, 'update']);
    Route::post('delete-campus', [App\Http\Controllers\CampusController::class, 'delete']);

    Route::get('estatus-ejemplares', [App\Http\Controllers\EstatusEjemplaresController::class, 'index']);
    Route::post('save-estatus-ejemplares', [App\Http\Controllers\EstatusEjemplaresController::class, 'store']);
    Route::post('update-estatus-ejemplares', [App\Http\Controllers\EstatusEjemplaresController::class, 'update']);
    Route::post('delete-estatus-ejemplares', [App\Http\Controllers\EstatusEjemplaresController::class, 'delete']);

    Route::get('facultades', [App\Http\Controllers\FacultadesController::class, 'index']);
    Route::post('save-facultad', [App\Http\Controllers\FacultadesController::class, 'store']);
    Route::post('update-facultad', [App\Http\Controllers\FacultadesController::class, 'update']);
    Route::post('delete-facultad', [App\Http\Controllers\FacultadesController::class, 'delete']);

    Route::get('identificaciones', [App\Http\Controllers\TipoIdentificacionController::class, 'index']);
    Route::post('save-identificacion', [App\Http\Controllers\TipoIdentificacionController::class, 'store']);
    Route::post('update-identificacion', [App\Http\Controllers\TipoIdentificacionController::class, 'update']);
    Route::post('delete-identificacion', [App\Http\Controllers\TipoIdentificacionController::class, 'delete']);

    Route::get('tipos-lectores', [App\Http\Controllers\TipoLectorController::class, 'index']);
    Route::post('save-tipos-lectores', [App\Http\Controllers\TipoLectorController::class, 'store']);
    Route::post('update-tipos-lectores', [App\Http\Controllers\TipoLectorController::class, 'update']);
    Route::post('delete-tipos-lectores', [App\Http\Controllers\TipoLectorController::class, 'delete']);

    Route::get('sucursales', [App\Http\Controllers\SucursalesController::class, 'index']);
    Route::post('save-sucursal', [App\Http\Controllers\SucursalesController::class, 'store']);
    Route::post('update-sucursal', [App\Http\Controllers\SucursalesController::class, 'update']);
    Route::post('delete-sucursal', [App\Http\Controllers\SucursalesController::class, 'delete']);

});
Route::group(['middleware' => ['auth','role:Super Admin|Admin Sucursales|Bibliotecario']], function () {
    Route::get('autores', [App\Http\Controllers\AutoresController::class, 'index']);
    Route::post('save-autor', [App\Http\Controllers\AutoresController::class, 'store']);
    Route::post('update-autor', [App\Http\Controllers\AutoresController::class, 'update']);
    Route::post('delete-autor', [App\Http\Controllers\AutoresController::class, 'delete']);

    Route::get('categorias', [App\Http\Controllers\CategoriasController::class, 'index']);
    Route::post('save-categoria', [App\Http\Controllers\CategoriasController::class, 'store']);
    Route::post('update-categoria', [App\Http\Controllers\CategoriasController::class, 'update']);
    Route::post('delete-categoria', [App\Http\Controllers\CategoriasController::class, 'delete']);
    
    Route::get('editoriales', [App\Http\Controllers\EditorialesController::class, 'index']);
    Route::post('save-editorial', [App\Http\Controllers\EditorialesController::class, 'store']);
    Route::post('update-editorial', [App\Http\Controllers\EditorialesController::class, 'update']);
    Route::post('delete-editorial', [App\Http\Controllers\EditorialesController::class, 'delete']);
    
    Route::get('crear-libros', [App\Http\Controllers\LibrosController::class, 'create']);
    Route::post('save-libro', [App\Http\Controllers\LibrosController::class, 'store']);
    Route::resource('libros', App\Http\Controllers\LibrosController::class);

    Route::post('save-ejemplar', [App\Http\Controllers\EjemplaresController::class, 'store']);
    Route::post('update-ejemplar', [App\Http\Controllers\EjemplaresController::class, 'update']);
    Route::post('delete-ejemplar', [App\Http\Controllers\EjemplaresController::class, 'delete']);
    Route::post('show-ejemplar', [App\Http\Controllers\EjemplaresController::class, 'show']);

    Route::get('lectores', [App\Http\Controllers\LectoresController::class, 'index']);
    Route::post('save-lector', [App\Http\Controllers\LectoresController::class, 'store']);
    Route::post('update-lector', [App\Http\Controllers\LectoresController::class, 'update']);
    Route::post('delete-lector', [App\Http\Controllers\LectoresController::class, 'delete']);
    Route::post('show-lector', [App\Http\Controllers\LectoresController::class, 'show']);

    Route::get('prestamos', [App\Http\Controllers\PrestamosController::class, 'index']);
    Route::post('save-prestamo', [App\Http\Controllers\PrestamosController::class, 'store']);
    Route::post('save-devolucion', [App\Http\Controllers\PrestamosController::class, 'devolver']);

    Route::get('reportes', [App\Http\Controllers\ReportesController::class, 'index']);
    Route::post('show-reporte', [App\Http\Controllers\ReportesController::class, 'show']);


});

Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/autores.blade.php
@extends('layouts.app')

@section('page-title')
Autores
@endsection

@section('content')
    <div class="row" id="app">
        <div class="col-md-12">
            <div class="card border-info shadow animate__animated animate__zoomInDown">
                <div class="card-header bg-info"></div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                @if(session()->get('success'))
                                    <div class="alert alert-success alert-fade">
                                        <i class="fa-solid fa-check"></i>
                                        {{ session()->get("success") }}
                                    </div>
                                  @endif
                                  @if(session()->get('error'))
                                    <div class="alert alert-danger alert-fade">
                                        <i class="fa-solid fa-xmark"></i>
                                        {{ session()->get("error") }}
                                    </div>
                                  @endif
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="row mb-3">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="d-grid col-6 mx-auto">
                                            <button class="btn btn-theme openModal" type="button" data-bs-toggle="modal" data-bs-target="#modalautors" data-op="1"><i class="fa-solid fa-circle-plus"></i> A&ntilde;adir</button>
                                          </div>
                                    </div>
                                </div>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered footable-p-f">
                                        <thead><tr><th scope="col">#</th><th scope="col">NOMBRE</th><th scope="col">EDITAR</th><th scope="col">ELIMINAR</th></tr></thead>
                                        <tbody>
                                            @php $i=1; @endphp
                                            @foreach($autores as $row)
                                                <tr><th scope="row">{{$i++}}</th><td>{{$row->nombre." ".$row->apellidos}}</td>
                                                    <td class="text-center"><button class="btn btn-warning openModal" data-bs-toggle="modal" data-bs-target="#modalautors" data-op="2"  data-autor="{{$row->apellidos." ".$row->nombre}}" data-id="{{$row->id}}" data-nombre="{{$row->nombre}}" data-apellidos="{{$row->apellidos}}" data-id="{{$row->id}}"><i class="fa-solid fa-pen-to-square"></i></button></td>
                                                    <td class="text-center">
                                                        <form id="frm_del_{{$row->id}}" method="POST" action="delete-autor">
                                                            @csrf
                                                            <input id="idAut" type="hidden" name="idAut" value="{{$row->id}}">
                                                            <button id="btnDel_{{$row->id}}" class="btn btn-danger delete" data-autor="{{$row->nombre." ".$row->apellidos}}" data-id="{{$row->id}}" type="button"><i class="fa-solid fa-trash-can"></i></button>
                                                        </form>
                                                    </td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <hr class="dropdown-divider d-block d-md-none mb-4 mb-md-0">
                            <div class="col-md-6">
                                <div class="row mb-3">
                                    <div class="col-md-5 offset-md-3 text-center">
                                        <label class="h3">TOP 10 </label>
                                    </div>
                                </div>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered footable-p-f">
                                        <thead><tr><th scope="col">#</th><th scope="col">AUTOR</th><th scope="col">TOTAL</th></thead>
                                        <tbody>
                                            @php $i=1; @endphp
                                            @foreach($top as $row)
                                                <tr><th scope="row">{{$i++}}</th><td>{{$row->autor}}</td><td>{{$row->total}}</td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="modalautors" class="modal fade" tabindex="-1">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">A&ntilde;adir autor</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="frmautor" method="POST" action="{{url('save-autor')}}">
                    @csrf
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-user-tie"></i></span>
                        <input id="nombre" type="text" class="form-control" name="nombre" placeholder="Nombre" maxlength="70" required>
                        <input id="idautor" type="hidden" name="idautor">
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-user-tie"></i></span>
                        <input id="apellidos" type="text" class="form-control" name="apellidos" placeholder="Apellidos" maxlength="80" required>
                    </div>
                    <div class="col-md-6 offset-md-2">
                        <div class="d-grid col-6 mx-auto">
                            <button id="btnSave" class="btn btn-theme" type="subtmit"><i class="fa-solid fa-floppy-disk"></i> Guardar</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </div>
          </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script type="text/javascript" src="{{ asset('js/autores.js') }}"></script>
@endsection

resources/views/bitacora.blade.php
@extends('layouts.app')

@section('page-title')
Bitácora
@endsection

@section('content')
<div class="row animate__animated animate__zoomInDown">
    <div class="col-md-12">
        <div class="card border-warning shadow">
            <div class="card-header bg-warning"></div>
            <div class="card-body">
                <div class="row mb-3">
                    <div class="col-md-4">
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-user"></i></span>
                            <select id="usuario" class="form-select">
                                <option value="">Selecciona usuario</option>
                                @if($users)
                                    @foreach($users as $row)
                                        <option value="{{$row->id}}">{{$row->name}}</option>
                                    @endforeach
                                @endif
                            </select>
                        </div>
                    </div>
                    <div class="col-md-4 ocultar">
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-calendar-alt"></i></span>
                            <input type="date" class="form-control" id="f_ini" name="f_ini" data-bs-toggle="tooltip" title="Fecha inicio">
                        </div>
                    </div>
                    <div class="col-md-4 ocultar">
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-calendar-alt"></i></span>
                            <input type="date" class="form-control" id="f_fin" name="f_fin" data-bs-toggle="tooltip" title="Fecha fin">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <button id="btnBuscar" class="btn btn-theme"><i class="fa-solid fa-magnifying-glass"></i> Consultar</button>
                    </div>
                </div>
                <hr class="dropdown-divider mt-3 mb-3 d-none">
                <div class="row resultados d-none" id="reporte">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table id="tabla" class="table table-bordered">
                                <thead><tr><th>#</th><th>USUARIO</th><th>ACCIÓN</th><th>FECHA</th><th>HORA</th></tr></thead>
                                <tbody id="tbody"></tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row d-none" id="load">
                    <div class="col-md-4 offset-md-4">
                        <img src="{{ asset('images/loading_'.rand(1, 12).'.gif')}}" class="img-fluid" height="100%" width="100%"> 
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
    <script type="text/javascript" src="{{ asset('js/bitacora.js') }}"></script>
@endsection

resources/views/campus.blade.php
@extends('layouts.app')

@section('page-title')
Campus
@endsection

@section('content')
    <div class="row" id="app">
        <div class="col-md-12">
            <div class="card border-info shadow animate__animated animate__zoomInDown">
                <div class="card-header bg-info"></div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                @if(session()->get('success'))
                                    <div class="alert alert-success alert-fade">
                                        <i class="fa-solid fa-check"></i>
                                        {{ session()->get("success") }}
                                    </div>
                                  @endif
                                  @if(session()->get('error'))
                                    <div class="alert alert-danger alert-fade">
                                        <i class="fa-solid fa-xmark"></i>
                                        {{ session()->get("error") }}
                                    </div>
                                  @endif
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="row mb-3">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="d-grid col-6 mx-auto">
                                            <button class="btn btn-theme openModal" type="button" data-bs-toggle="modal" data-bs-target="#modalcampus" data-op="1"><i class="fa-solid fa-circle-plus"></i> A&ntilde;adir</button>
                                        </div>
                                    </div>
                                </div>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered footable-p-f">
                                        <thead><tr><th scope="col">#</th><th scope="col">NOMBRE</th><th scope="col">EDITAR</th><th scope="col">ELIMINAR</th></tr></thead>
                                        <tbody>
                                            @php $i=1; @endphp
                                            @foreach($campus as $row)
                                                <tr><th scope="row">{{$i++}}</th><td>{{$row->campus}}</td>
                                                    <td class="text-center"><button class="btn btn-warning openModal" data-bs-toggle="modal" data-bs-target="#modalcampus" data-op="2" data-campus="{{$row->campus}}" data-id="{{$row->id}}"><i class="fa-solid fa-pen-to-square"></i></button></td>
                                                    <td class="text-center">
                                                        <form id="frm_del_{{$row->id}}" method="POST" action="delete-campus">
                                                            @csrf
                                                            <input id="idCam" type="hidden" name="idCam" value="{{$row->id}}">
                                                            <button id="btnDel_{{$row->id}}" class="btn btn-danger delete" data-campus="{{$row->campus}}" data-id="{{$row->id}}" type="button"><i class="fa-solid fa-trash-can"></i></button>
                                                        </form>
                                                    </td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <hr class="dropdown-divider d-block d-md-none mb-4 mb-md-0">
                            <div class="col-md-6">
                                <div class="row mb-3">
                                    <div class="col-md-5 offset-md-3 text-center">
                                        <label class="h3">TOP 10 </label>
                                    </div>
                                </div>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered footable-p-f">
                                        <thead><tr><th scope="col">#</th><th scope="col">CAMPUS</th><th scope="col">TOTAL</th></thead>
                                        <tbody>
                                            @php $i=1; @endphp
                                            @foreach($top as $row)
                                                <tr><th scope="row">{{$i++}}</th><td>{{$row->campus}}</td><td>{{$row->total}}</td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="modalcampus" class="modal fade" tabindex="-1">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">A&ntilde;adir campus</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="frmcampus" method="POST" action="{{url('save-campus')}}">
                    @csrf
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-school"></i></span>
                        <input id="campus" type="text" class="form-control" name="campus" placeholder="Campus" maxlength="50" required>
                        <input id="idcampus" type="hidden" name="idcampus">
                    </div>
                    <div class="col-md-6 offset-md-2">
                        <div class="d-grid col-6 mx-auto">
                            <button id="btnSave" class="btn btn-theme" type="subtmit"><i class="fa-solid fa-floppy-disk"></i> Guardar</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </div>
          </div>
        </div>
      </div>
@endsection

@section('scripts')
    <script type="text/javascript" src="{{ asset('js/campus.js') }}"></script>
@endsection

resources/views/libros.blade.php
@extends('layouts.app')

@section('page-title')
Libros
@endsection

@section('style')
    <link href="{{ asset('css/libros.css') }}" rel="stylesheet">
@endsection

@section('content')
    <div class="row animate__animated animate__zoomInDown" id="app">
        <div class="col-md-12">
            <div class="card border-warning shadow">
                <div class="card-header bg-warning"></div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                @if(session()->get('success'))
                                    <div class="alert alert-success alert-fade">
                                        <i class="fa-solid fa-check"></i>
                                        {{ session()->get("success") }}
                                    </div>
                                  @endif
                                  @if(session()->get('error'))
                                    <div class="alert alert-danger alert-fade">
                                        <i class="fa-solid fa-xmark"></i>
                                        {{ session()->get("error") }}
                                    </div>
                                  @endif
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-md-4 offset-md-4">
                                <div class="d-grid col-6 mx-auto">
                                    <a class="btn btn-theme" href="{{url('crear-libros')}}" ><i class="fa-solid fa-circle-plus"></i> A&ntilde;adir</a>
                                  </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered footable-p-f">
                                        <thead>
                                            <tr>
                                                <th scope="col">#</th>
                                                <th data-breakpoints="xs"  scope="col">ISBN</th>
                                                <th scope="col">TITULO</th>
                                                <th data-breakpoints="xs" scope="col">SUBTITULO</th>
                                                <th data-breakpoints="xs" scope="col">AUTORES</th>
                                                <th data-breakpoints="xs" scope="col">P&Aacute;GINAS</th>
                                                <th data-breakpoints="xs" scope="col">A&Ntilde;O</th>
                                                <th data-breakpoints="xs" scope="col">EDITORIAL</th>
                                                <th data-breakpoints="xs sm" scope="col">CATEGORIA</th>
                                                <th data-breakpoints="xs sm" scope="col"></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @php $i=1; @endphp
                                            @foreach($libros as $row)
                                                <tr>
                                                    <td scope="row">{{$i++}}</td>
                                                    <td>{{$row->isbn}}</td>
                                                    <td>{{$row->titulo}}</td>
                                                    <td>{{$row->subtitulo}}</td>
                                                    <td>{{$row->autores}}</td>
                                                    <td>{{$row->paginas}}</td>
                                                    <td>{{$row->publicacion}}</td>
                                                    <td>{{$row->editorial}}</td>
                                                    <td>{{$row->categoria}}</td>
                                                    <td><a class="btn btn-info" href="{{ route('libros.show',$row->id) }}"><i class="fa-solid fa-circle-info"></i></a></td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
@endsection